### ISSUE TITLE
微信打开正常显示，切换到浏览器打开却无法正常显示

### ISSUE THREAD

**Issue by lebonnuit** [zerosoul/honeyed-words-generator#2]
1. 微信打开界面：
![84E57A21-7FCB-4D58-853B-B95610B83BF3](https://user-images.githubusercontent.com/56405349/74586890-53e9cf80-5027-11ea-8d51-0cf2d6e7ef62.png)

2. Alooj浏览器打开界面
![F12FE8DF-4EEA-4B54-B7B3-B3805109DD01](https://user-images.githubusercontent.com/56405349/74586911-901d3000-5027-11ea-9170-9589b6a58e87.png)

3. 点击换一句的时候会短暂闪现以下画面：
![8A4E1643-80B1-417D-AAF5-E8FA83B13411](https://user-images.githubusercontent.com/56405349/74586917-a3300000-5027-11ea-9dd4-8b5bfb85ce29.png)

**Comment by zerosoul** [comment]
> 2\. Alooj

Alooj 是什么？第一次听说🤣。这个现象看应该是某个css静态资源没正确加载，不好意思，Alooj太小众了，不考虑排查和修复了。
